// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using yazlab3.web.Data;

#nullable disable

namespace yazlab3.web.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251224182622_Cargo3")]
    partial class Cargo3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Route", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("TotalCost")
                        .HasColumnType("float");

                    b.Property<double>("TotalDistanceKm")
                        .HasColumnType("float");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VehicleId");

                    b.ToTable("Routes");
                });

            modelBuilder.Entity("RouteStation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int>("RouteId")
                        .HasColumnType("int");

                    b.Property<int>("StationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RouteId");

                    b.HasIndex("StationId");

                    b.ToTable("RouteStations");
                });

            modelBuilder.Entity("Station", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Stations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Latitude = 40.715000000000003,
                            Longitude = 29.927,
                            Name = "Başiskele"
                        },
                        new
                        {
                            Id = 2,
                            Latitude = 40.819000000000003,
                            Longitude = 29.373000000000001,
                            Name = "Çayırova"
                        },
                        new
                        {
                            Id = 3,
                            Latitude = 40.773000000000003,
                            Longitude = 29.399999999999999,
                            Name = "Darıca"
                        },
                        new
                        {
                            Id = 4,
                            Latitude = 40.756,
                            Longitude = 29.829999999999998,
                            Name = "Derince"
                        },
                        new
                        {
                            Id = 5,
                            Latitude = 40.786999999999999,
                            Longitude = 29.544,
                            Name = "Dilovası"
                        },
                        new
                        {
                            Id = 6,
                            Latitude = 40.802,
                            Longitude = 29.43,
                            Name = "Gebze"
                        },
                        new
                        {
                            Id = 7,
                            Latitude = 40.716999999999999,
                            Longitude = 29.818000000000001,
                            Name = "Gölcük"
                        },
                        new
                        {
                            Id = 8,
                            Latitude = 41.07,
                            Longitude = 30.149999999999999,
                            Name = "Kandıra"
                        },
                        new
                        {
                            Id = 9,
                            Latitude = 40.692,
                            Longitude = 29.616,
                            Name = "Karamürsel"
                        },
                        new
                        {
                            Id = 10,
                            Latitude = 40.753,
                            Longitude = 30.015999999999998,
                            Name = "Kartepe"
                        },
                        new
                        {
                            Id = 11,
                            Latitude = 40.771000000000001,
                            Longitude = 29.742999999999999,
                            Name = "Körfez"
                        },
                        new
                        {
                            Id = 12,
                            Latitude = 40.765000000000001,
                            Longitude = 29.940000000000001,
                            Name = "İzmit"
                        },
                        new
                        {
                            Id = 99,
                            Latitude = 40.822200000000002,
                            Longitude = 29.921700000000001,
                            Name = "Umuttepe"
                        });
                });

            modelBuilder.Entity("Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CapacityKg")
                        .HasColumnType("int");

                    b.Property<bool>("IsRented")
                        .HasColumnType("bit");

                    b.Property<double>("RentalCost")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Vehicles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CapacityKg = 500,
                            IsRented = false,
                            RentalCost = 0.0
                        },
                        new
                        {
                            Id = 2,
                            CapacityKg = 750,
                            IsRented = false,
                            RentalCost = 0.0
                        },
                        new
                        {
                            Id = 3,
                            CapacityKg = 1000,
                            IsRented = false,
                            RentalCost = 0.0
                        });
                });

            modelBuilder.Entity("yazlab3.web.Models.CargoRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CargoCount")
                        .HasColumnType("int");

                    b.Property<string>("CargoType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReceiverName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("StationId")
                        .HasColumnType("int");

                    b.Property<int>("TotalWeightKg")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StationId");

                    b.ToTable("CargoRequests");
                });

            modelBuilder.Entity("yazlab3.web.Models.StationDistance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("DistanceKm")
                        .HasColumnType("float");

                    b.Property<int>("FromStationId")
                        .HasColumnType("int");

                    b.Property<int>("ToStationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FromStationId");

                    b.HasIndex("ToStationId");

                    b.ToTable("StationDistances");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DistanceKm = 10.0,
                            FromStationId = 1,
                            ToStationId = 12
                        },
                        new
                        {
                            Id = 2,
                            DistanceKm = 15.0,
                            FromStationId = 1,
                            ToStationId = 7
                        },
                        new
                        {
                            Id = 3,
                            DistanceKm = 12.0,
                            FromStationId = 1,
                            ToStationId = 10
                        },
                        new
                        {
                            Id = 4,
                            DistanceKm = 15.0,
                            FromStationId = 7,
                            ToStationId = 1
                        },
                        new
                        {
                            Id = 5,
                            DistanceKm = 18.0,
                            FromStationId = 7,
                            ToStationId = 9
                        },
                        new
                        {
                            Id = 6,
                            DistanceKm = 18.0,
                            FromStationId = 9,
                            ToStationId = 7
                        },
                        new
                        {
                            Id = 7,
                            DistanceKm = 10.0,
                            FromStationId = 12,
                            ToStationId = 1
                        },
                        new
                        {
                            Id = 8,
                            DistanceKm = 10.0,
                            FromStationId = 12,
                            ToStationId = 10
                        },
                        new
                        {
                            Id = 9,
                            DistanceKm = 13.0,
                            FromStationId = 12,
                            ToStationId = 4
                        },
                        new
                        {
                            Id = 10,
                            DistanceKm = 40.0,
                            FromStationId = 12,
                            ToStationId = 8
                        },
                        new
                        {
                            Id = 11,
                            DistanceKm = 13.0,
                            FromStationId = 4,
                            ToStationId = 12
                        },
                        new
                        {
                            Id = 12,
                            DistanceKm = 8.0,
                            FromStationId = 4,
                            ToStationId = 11
                        },
                        new
                        {
                            Id = 13,
                            DistanceKm = 8.0,
                            FromStationId = 11,
                            ToStationId = 4
                        },
                        new
                        {
                            Id = 14,
                            DistanceKm = 16.0,
                            FromStationId = 11,
                            ToStationId = 5
                        },
                        new
                        {
                            Id = 15,
                            DistanceKm = 16.0,
                            FromStationId = 5,
                            ToStationId = 11
                        },
                        new
                        {
                            Id = 16,
                            DistanceKm = 10.0,
                            FromStationId = 5,
                            ToStationId = 6
                        },
                        new
                        {
                            Id = 17,
                            DistanceKm = 10.0,
                            FromStationId = 6,
                            ToStationId = 5
                        },
                        new
                        {
                            Id = 18,
                            DistanceKm = 7.0,
                            FromStationId = 6,
                            ToStationId = 2
                        },
                        new
                        {
                            Id = 19,
                            DistanceKm = 6.0,
                            FromStationId = 6,
                            ToStationId = 3
                        },
                        new
                        {
                            Id = 20,
                            DistanceKm = 7.0,
                            FromStationId = 2,
                            ToStationId = 6
                        },
                        new
                        {
                            Id = 21,
                            DistanceKm = 9.0,
                            FromStationId = 2,
                            ToStationId = 3
                        },
                        new
                        {
                            Id = 22,
                            DistanceKm = 6.0,
                            FromStationId = 3,
                            ToStationId = 6
                        },
                        new
                        {
                            Id = 23,
                            DistanceKm = 9.0,
                            FromStationId = 3,
                            ToStationId = 2
                        },
                        new
                        {
                            Id = 24,
                            DistanceKm = 40.0,
                            FromStationId = 8,
                            ToStationId = 12
                        },
                        new
                        {
                            Id = 25,
                            DistanceKm = 10.0,
                            FromStationId = 10,
                            ToStationId = 12
                        },
                        new
                        {
                            Id = 26,
                            DistanceKm = 12.0,
                            FromStationId = 10,
                            ToStationId = 1
                        },
                        new
                        {
                            Id = 100,
                            DistanceKm = 15.0,
                            FromStationId = 99,
                            ToStationId = 12
                        },
                        new
                        {
                            Id = 101,
                            DistanceKm = 15.0,
                            FromStationId = 12,
                            ToStationId = 99
                        });
                });

            modelBuilder.Entity("yazlab3.web.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Password = "123",
                            Role = "Admin",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            Password = "123",
                            Role = "User",
                            Username = "user1"
                        },
                        new
                        {
                            Id = 3,
                            Password = "123",
                            Role = "User",
                            Username = "user2"
                        });
                });

            modelBuilder.Entity("Route", b =>
                {
                    b.HasOne("Vehicle", "Vehicle")
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("RouteStation", b =>
                {
                    b.HasOne("Route", "Route")
                        .WithMany("RouteStations")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Station", "Station")
                        .WithMany()
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Route");

                    b.Navigation("Station");
                });

            modelBuilder.Entity("yazlab3.web.Models.CargoRequest", b =>
                {
                    b.HasOne("Station", "Station")
                        .WithMany()
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Station");
                });

            modelBuilder.Entity("yazlab3.web.Models.StationDistance", b =>
                {
                    b.HasOne("Station", "FromStation")
                        .WithMany()
                        .HasForeignKey("FromStationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Station", "ToStation")
                        .WithMany()
                        .HasForeignKey("ToStationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FromStation");

                    b.Navigation("ToStation");
                });

            modelBuilder.Entity("Route", b =>
                {
                    b.Navigation("RouteStations");
                });
#pragma warning restore 612, 618
        }
    }
}
